SET NOCOUNT ON;
SET STATISTICS TIME ON;
SET STATISTICS IO ON;
DBCC FREEPROCCACHE WITH NO_INFOMSGS;
SELECT COUNT(*) FROM exercises WHERE lesson_id = 91900 AND exercise_type = N'MULTIPLE_CHOICE' ORDER BY order_index;
SELECT TOP 20 exercise_id FROM exercises WHERE lesson_id = 91900 AND exercise_type = N'MULTIPLE_CHOICE' ORDER BY order_index;
SET STATISTICS IO OFF;
SET STATISTICS TIME OFF;
