const H = require("./lib.js");
const API = "http://localhost:8080", APP = "http://localhost:5173";
(async () => {
  const admin = await H.login("admin@gmail.com", "123456");
  const stamp = Date.now();
  const r = await fetch(API + "/api/v1/admin/video-lessons", { method: "POST", headers: { Authorization: "Bearer " + admin, "Content-Type": "application/json" }, body: JSON.stringify({ title: "ZZ dbg edit " + stamp, description: "seed", youtubeUrl: "https://www.youtube.com/watch?v=2VeQTuSSiI0", level: "ELEMENTARY", isPublished: true, transcript: [{ start: 0, end: 2, textEn: "Keep me one." }, { start: 2, end: 4, textEn: "Keep me two." }] }) });
  const seed = await r.json(); console.log("seed id", seed.id);
  const browser = await H.pw.chromium.launch({ headless: true });
  const ctx = await H.mkContext(browser, admin, { width: 1440, height: 950 });
  const page = await ctx.newPage();
  page.on("console", m => console.log("  console." + m.type() + ":", m.text().slice(0, 200)));
  page.on("request", req => { if (req.url().includes("/api/v1/admin/video-lessons")) console.log("  REQ", req.method(), req.url().replace(API, ""), (req.postData() || "").slice(0, 200)); });
  page.on("response", res => { if (res.url().includes("/api/v1/admin/video-lessons")) console.log("  RES", res.status()); });
  await page.goto(APP + "/login", { waitUntil: "domcontentloaded" });
  await page.waitForTimeout(1500);
  await page.fill('input[type="email"], input[name="email"]', "admin@gmail.com");
  await page.fill('input[type="password"]', "123456");
  await page.click('button[type="submit"]');
  await page.waitForTimeout(4000);
  await page.goto(APP + "/admin/videos", { waitUntil: "domcontentloaded" });
  await page.waitForTimeout(3000);
  const row = page.locator("tr", { hasText: "ZZ dbg edit " + stamp }).first();
  await row.getByRole("button", { name: "Sửa" }).click();
  await page.waitForTimeout(800);
  const inputs = await page.evaluate(() => [...document.querySelectorAll("form#video-lesson-form input, form#video-lesson-form textarea, form#video-lesson-form select")].map(e => ({ tag: e.tagName, id: e.id, type: e.type, val: String(e.value).slice(0, 40) })));
  console.log("FORM FIELDS", JSON.stringify(inputs, null, 1));
  const saveBtns = await page.evaluate(() => [...document.querySelectorAll("button")].map(b => b.innerText.trim()).filter(t => t.includes("Lưu")));
  console.log("save buttons", JSON.stringify(saveBtns));
  await page.locator("form#video-lesson-form input").first().fill("ZZ dbg edit " + stamp + " v2");
  await page.getByRole("button", { name: /Lưu bài học/ }).click();
  await page.waitForTimeout(3000);
  const after = await page.evaluate(() => ({ err: (document.querySelector("[role=alert]") || {}).innerText || null, body: document.body.innerText.slice(0, 200) }));
  console.log("AFTER", JSON.stringify(after));
  await fetch(API + "/api/v1/admin/video-lessons/" + seed.id, { method: "DELETE", headers: { Authorization: "Bearer " + admin } });
  await browser.close();
})().catch(e => { console.error("FATAL", e.message); process.exit(1); });
