package com.datn.engflow.service;

import com.datn.engflow.exception.BadRequestException;
import com.datn.engflow.model.dto.video.VideoDtos.TranscriptLine;
import com.datn.engflow.service.assessment.LlmChatClient;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpHeaders;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;
import org.springframework.web.reactive.function.client.WebClientResponseException;

import java.time.Duration;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Fetches an existing YouTube transcript (auto or human captions) through the
 * public InnerTube player endpoint, then has the local LLM translate the cues
 * to Vietnamese in one call. Title and description come along for free so the
 * admin form can be pre-filled.
 *
 * <p>This is a best-effort integration: YouTube can throttle or change the
 * player response at any time, so every failure surfaces as a clear
 * {@link BadRequestException} and the admin keeps the manual SRT paste as a
 * fallback.</p>
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class YouTubeTranscriptService {

    private static final String INNERTUBE_URL = "https://www.youtube.com/youtubei/v1/player";
    private static final String ANDROID_CLIENT_CONTEXT =
            "{\"context\":{\"client\":{\"clientName\":\"ANDROID\",\"clientVersion\":\"20.10.38\",\"androidSdkVersion\":30,\"hl\":\"en\"}}}";

    private static final Pattern VIDEO_ID = Pattern.compile(
            "(?:v=|embed/|shorts/|youtu\\.be/|live/)([A-Za-z0-9_-]{11})");

    /** Legacy srv XML: <text start="12.52" dur="2.72">Hello world</text> (seconds). */
    private static final Pattern SRV_TEXT_LINE = Pattern.compile(
            "<text\\b([^>]*)>(.*?)</text>",
            Pattern.DOTALL);

    /** Current Android InnerTube XML (format=3): <p t="1360" d="1680">Hello</p> (milliseconds). */
    private static final Pattern P_TAG_LINE = Pattern.compile(
            "<p\\b([^>]*)>(.*?)</p>",
            Pattern.DOTALL);

    /** Matches start/dur (seconds) or t/d (milliseconds) attributes anywhere inside the tag. */
    private static final Pattern TIME_ATTR = Pattern.compile("\\b(start|dur|t|d)=\"([0-9.]+)\"");

    /** Pure music markers like "[Music]", "(♪)" or "♪♪♪" are noise for shadowing practice. */
    private static final Pattern MUSIC_MARKER = Pattern.compile(
            "^[\\s\\p{Punct}♪♫♩♬\\[\\]]*(\\[(?i:music|applause|laughter|cheering)\\]|[♪♫♩♬\\s\\p{Punct}]+)[\\s\\p{Punct}♪♫♩♬\\[\\]]*$");

    /** True when the line is only a music/noise marker — no real spoken words. */
    static boolean isMusicMarkerOnly(String text) {
        if (text == null || text.isBlank()) {
            return true;
        }
        return text.codePoints().allMatch(c ->
                Character.isWhitespace(c) || !Character.isLetterOrDigit(c))
                || MUSIC_MARKER.matcher(text.trim()).matches();
    }

    private static final String TRANSLATE_SYSTEM = """
            Bạn dịch phụ đề từ tiếng Anh sang TIẾNG VIỆT (ngôn ngữ Việt Nam, bảng chữ Latinh có dấu).
            TUYỆT ĐỐI KHÔNG dịch sang tiếng Trung, tiếng Nhật hay bất kỳ ngôn ngữ nào khác.
            Phong cách: tự nhiên, ngắn gọn, phù hợp hội thoại nói. Giữ tên riêng và con số.
            Trả về CHÍNH XÁC một mảng JSON các chuỗi tiếng Việt, thứ tự giống đầu vào. Không markdown, không giải thích.

            Ví dụ:
            Input: ["We're no strangers to love", "You know the rules and so do I"]
            Output: ["Chúng ta chẳng còn xa lạ gì với tình yêu", "Bạn biết những quy tắc và tôi cũng vậy"]
            """;

    private final ObjectMapper objectMapper;
    private final LlmChatClient llm;

    private WebClient webClient;

    private WebClient client() {
        if (webClient == null) {
            this.webClient = WebClient.builder()
                    .defaultHeader(HttpHeaders.CONTENT_TYPE, "application/json")
                    .defaultHeader(HttpHeaders.USER_AGENT,
                            "com.google.android.youtube/20.10.38 (Linux; U; Android 11) gzip")
                    .build();
        }
        return webClient;
    }

    /** Result handed back to the admin form. */
    public record YoutubeTranscriptResult(
            String videoId, String title, String description,
            String language, boolean autoGenerated, List<TranscriptLine> lines) {
    }

    /**
     * Fetches captions for {@code youtubeUrl} and translates every cue to
     * Vietnamese via the local LLM (single call, English and Vietnamese in
     * one step).
     */
    public YoutubeTranscriptResult fetchAndTranslate(String youtubeUrl) {
        String videoId = extractVideoId(youtubeUrl);
        Captions captions = fetchCaptionTrack(videoId);
        List<TranscriptLine> lines = parseXmlCaptions(captions.xml());
        if (lines.isEmpty()) {
            throw new BadRequestException("Video này không có phụ đề nào để lấy (cả phụ đề tự động)");
        }

        List<TranscriptLine> translated = translateLines(lines);
        return new YoutubeTranscriptResult(videoId, captions.title(), captions.description(),
                captions.language(), captions.autoGenerated(), translated);
    }

    String extractVideoId(String url) {
        if (url == null || url.isBlank()) {
            throw new BadRequestException("Thiếu link YouTube");
        }
        if (url.matches("[A-Za-z0-9_-]{11}")) {
            return url;
        }
        Matcher m = VIDEO_ID.matcher(url);
        if (!m.find()) {
            throw new BadRequestException("Link YouTube không hợp lệ");
        }
        return m.group(1);
    }

    private record Captions(String title, String description, String language, boolean autoGenerated, String xml) {
    }

    /**
     * Calls the InnerTube player endpoint (Android client — least likely to
     * require PoTokens) and picks the best caption track: manual English
     * first, then any manual track, then auto-generated.
     */
    private Captions fetchCaptionTrack(String videoId) {
        // InnerTube payload: inject videoId as the first JSON key.
        String payload = ANDROID_CLIENT_CONTEXT.replaceFirst("\\{",
                "\\{\"videoId\":\"" + videoId + "\",");
        String body;
        try {
            body = client().post()
                    .uri(INNERTUBE_URL + "?prettyPrint=false")
                    .bodyValue(payload)
                    .retrieve()
                    .bodyToMono(String.class)
                    .timeout(Duration.ofSeconds(20))
                    .block();
        } catch (WebClientResponseException ex) {
            log.warn("InnerTube returned {} for video {}", ex.getStatusCode(), videoId);
            throw new BadRequestException("YouTube từ chối truy vấn (" + ex.getStatusCode() + ") — thử lại sau hoặc dán phụ đề tay");
        } catch (Exception ex) {
            log.warn("InnerTube call failed for video {}: {}", videoId, ex.getMessage());
            throw new BadRequestException("Không kết nối được YouTube — kiểm tra link hoặc mạng");
        }
        if (body == null || body.isBlank()) {
            throw new BadRequestException("YouTube không trả dữ liệu cho video này");
        }

        JsonNode root;
        try {
            root = objectMapper.readTree(body);
        } catch (Exception ex) {
            throw new BadRequestException("Phản hồi YouTube không đọc được");
        }
        if (root.path("playabilityStatus").path("status").asText("").equals("ERROR")) {
            throw new BadRequestException("Video không xem được (chặn vùng / riêng tư / đã xóa)");
        }

        String title = root.path("videoDetails").path("title").asText(null);
        String description = root.path("videoDetails").path("shortDescription").asText(null);
        JsonNode tracks = root.path("captions").path("playerCaptionsTracklistRenderer").path("captionTracks");
        if (!tracks.isArray() || tracks.isEmpty()) {
            throw new BadRequestException("Video này không có phụ đề (cả tự động). Hãy dán file .srt tay.");
        }

        JsonNode best = null;
        JsonNode anyManual = null;
        JsonNode anyAuto = null;
        for (JsonNode t : tracks) {
            boolean auto = t.path("kind").asText("").equals("asr");
            if (!auto && anyManual == null) {
                anyManual = t;
            }
            if (auto && anyAuto == null) {
                anyAuto = t;
            }
            String code = t.path("languageCode").asText("");
            if (!auto && (code.startsWith("en"))) {
                best = t;
                break;
            }
        }
        if (best == null) {
            best = anyManual != null ? anyManual : anyAuto;
        }
        if (best == null) {
            throw new BadRequestException("Video này không có phụ đề (cả tự động). Hãy dán file .srt tay.");
        }

        boolean auto = best.path("kind").asText("").equals("asr");
        String language = best.path("languageCode").asText("en");
        String baseUrl = best.path("baseUrl").asText(null);
        if (baseUrl == null || baseUrl.isBlank()) {
            throw new BadRequestException("Không đọc được đường dẫn phụ đề của video này");
        }
        String raw = client().get()
                .uri(baseUrl)
                .retrieve()
                .bodyToMono(String.class)
                .timeout(Duration.ofSeconds(20))
                .block();
        if (raw == null || raw.isBlank()) {
            throw new BadRequestException("Không tải được nội dung phụ đề từ YouTube");
        }
        return new Captions(title, description, language, auto, raw);
    }

    /** Parses YouTube caption content: XML srv (default) or json3 when requested. */
    static List<TranscriptLine> parseXmlCaptions(String content) {
        String trimmed = content == null ? "" : content.trim();
        if (trimmed.startsWith("{")) {
            return parseJson3Captions(trimmed);
        }
        return parseSrvXmlCaptions(trimmed);
    }

    /** Parses YouTube json3 caption format into timed lines. */
    static List<TranscriptLine> parseJson3Captions(String json3) {
        List<TranscriptLine> lines = new ArrayList<>();
        try {
            ObjectMapper mapper = new ObjectMapper();
            JsonNode root = mapper.readTree(json3);
            for (JsonNode event : root.path("events")) {
                double start = event.path("tStartMs").asDouble(0) / 1000.0;
                double duration = event.path("dDurationMs").asDouble(0) / 1000.0;
                JsonNode segs = event.path("segs");
                if (!segs.isArray() || segs.isEmpty()) {
                    continue;
                }
                StringBuilder text = new StringBuilder();
                for (JsonNode seg : segs) {
                    text.append(seg.path("utf8").asText(""));
                }
                String cleaned = text.toString().replace("\n", " ").replaceAll("\\s+", " ").trim();
                if (cleaned.isEmpty()) {
                    continue;
                }
                double end = start + (duration > 0 ? duration : 2.0);
                if (duration <= 0 && !lines.isEmpty()) {
                    // Extend the previous cue to cover this one when durations are missing.
                    TranscriptLine prev = lines.remove(lines.size() - 1);
                    lines.add(new TranscriptLine(prev.start(), start, prev.textEn(), prev.textVi()));
                }
                lines.add(new TranscriptLine(start, end, cleaned, null));
            }
        } catch (Exception ex) {
            log.warn("json3 caption parse failed: {}", ex.getMessage());
        }
        return lines;
    }

    /**
     * Parses YouTube XML captions in either shape:
     * legacy srv (&lt;text start="1.2" dur="2"&gt;, seconds) or the current
     * Android InnerTube format=3 (&lt;p t="1200" d="800"&gt;, milliseconds).
     */
    static List<TranscriptLine> parseSrvXmlCaptions(String xml) {
        List<TranscriptLine> lines = new ArrayList<>();
        boolean pFormat = xml.contains("<p ");
        Matcher m = (pFormat ? P_TAG_LINE : SRV_TEXT_LINE).matcher(xml);
        while (m.find()) {
            double start = 0;
            double dur = 2.0;
            Matcher attrs = TIME_ATTR.matcher(m.group(1));
            while (attrs.find()) {
                try {
                    double value = Double.parseDouble(attrs.group(2));
                    switch (attrs.group(1)) {
                        case "start", "t" -> start = pFormat ? value / 1000.0 : value;
                        case "dur", "d" -> dur = pFormat ? value / 1000.0 : value;
                        default -> { }
                    }
                } catch (NumberFormatException ex) {
                    // keep defaults
                }
            }
            // Strip real markup tags first, THEN unescape entities — otherwise an
            // unescaped "&lt;line&gt;" would be eaten by the tag stripper.
            String text = m.group(2)
                    .replaceAll("<[^>]+>", " ")
                    .replace("&amp;", "&").replace("&lt;", "<").replace("&gt;", ">")
                    .replace("&quot;", "\"").replace("&#39;", "'").replace("&apos;", "'")
                    .replace("\n", " ")
                    .replaceAll("\\s+", " ")
                    .trim();
            if (text.isEmpty() || isMusicMarkerOnly(text)) {
                continue;
            }
            lines.add(new TranscriptLine(start, start + dur, text, null));
        }
        return lines;
    }

    /**
     * Translates in chunks of {@value #BATCH_SIZE} lines: small local models
     * lose the format/language instructions on long arrays (attention decay)
     * and start parroting English back, so one call per ~25 lines keeps the
     * output reliable.
     */
    private static final int BATCH_SIZE = 25;

    /** One LLM call per batch; falls back to null textVi on failure. */
    private List<TranscriptLine> translateLines(List<TranscriptLine> lines) {
        List<TranscriptLine> result = new ArrayList<>(lines);
        int total = Math.min(lines.size(), 400);
        boolean anyTranslated = false;
        for (int from = 0; from < total; from += BATCH_SIZE) {
            int to = Math.min(from + BATCH_SIZE, total);
            List<TranscriptLine> batch = lines.subList(from, to);
            try {
                List<String> vi = translateBatch(batch);
                if (vi == null) {
                    continue;
                }
                for (int i = 0; i < batch.size() && i < vi.size(); i++) {
                    String text = vi.get(i) == null ? "" : vi.get(i).trim();
                    if (!text.isEmpty()) {
                        TranscriptLine original = result.get(from + i);
                        result.set(from + i, new TranscriptLine(original.start(), original.end(), original.textEn(), text));
                        anyTranslated = true;
                    }
                }
            } catch (Exception ex) {
                log.warn("YouTube caption translation failed for batch [{}-{}): {}",
                        from, to, ex.getMessage());
            }
        }
        return result;
    }

    /**
     * Translates one batch with a language check and one strong retry.
     *
     * @return Vietnamese lines aligned with the batch, or {@code null} when the
     *         model would not produce Vietnamese
     */
    private List<String> translateBatch(List<TranscriptLine> batch) throws Exception {
        StringBuilder array = new StringBuilder("[");
        for (int i = 0; i < batch.size(); i++) {
            if (i > 0) {
                array.append(',');
            }
            array.append('"').append(batch.get(i).textEn()
                    .replace("\\", "\\\\").replace("\"", "\\\"")).append('"');
        }
        array.append(']');

        String userPrompt = "Dịch mảng JSON sau sang tiếng Việt:\n" + array;
        List<String> vi = requestTranslation(userPrompt);
        if (!looksVietnamese(vi)) {
            // Small model sometimes ignores the language instruction — one strong retry.
            log.warn("Translation output not Vietnamese; retrying with stronger instruction");
            vi = requestTranslation(userPrompt
                    + "\n\nQUAN TRỌNG: Kết quả PHẢI là tiếng Việt (ví dụ: \"Chào các bạn\", \"Hôm nay học gì\"). "
                    + "KHÔNG dùng chữ Hán/Tiếng Trung.");
            if (!looksVietnamese(vi)) {
                return null;
            }
        }
        return vi;
    }

    private List<String> requestTranslation(String userPrompt) throws Exception {
        String raw = llm.completeWithRetry(TRANSLATE_SYSTEM, userPrompt);
        int start = raw.indexOf('[');
        int end = raw.lastIndexOf(']');
        if (start < 0 || end <= start) {
            throw new IllegalStateException("no JSON array in translation output");
        }
        return objectMapper.readValue(raw.substring(start, end + 1),
                new com.fasterxml.jackson.core.type.TypeReference<List<String>>() {
                });
    }

    /** True when at least a third of the lines carry Vietnamese diacritics. */
    static boolean looksVietnamese(List<String> lines) {
        if (lines == null || lines.isEmpty()) {
            return false;
        }
        long withDiacritics = lines.stream()
                .filter(t -> t != null && t.chars().anyMatch(c -> c >= 0x00C0 && c <= 0x1EF9))
                .count();
        return withDiacritics * 3 >= lines.size();
    }
}
